# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61c9049b48dab10b357a8ecadddae50cc03131b1c77a4810994a945402f9c1bafcf47b9fbfcd7553345cf635eb13d7d2896099b559f6d014abaf5ad2faf34d9

test:
  secret_key_base: 4f0d3512cd4eb70c745531978a707f840e4ec4c950dd7012ad7bc8c202a5e7b934f6deaa4b27247628eb13ce1c42ecc2c262ebdda955167d836b8a1e565e2131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
